version: '3.9'

services:
  app:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: "rtp-webrtc-golang"
    ports:
      - 5004:5004
    network_mode: "host"
    stdin_open: true
    tty: true

    # Mount point for offer and answers.
    volumes:
      - /home/bms/webrtc-go-alex/sdps:/sdps
